version: "2"

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - certs-volume:/data
    networks:
      - web

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "1000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data portainer/portainer
    entrypoint: /portainer -p :80
    networks:
      - web

volumes:
  certs-volume:
  portainer_data:

networks:
  web:
    external: true
