version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: fading-flame.com
    container_name: mailserver
    env_file: mailserver.env
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
      - "110:110"  # POP3
      - "995:995"  # POP3
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - /usr/mailconfig/:/tmp/docker-mailserver/
      - certs-volume:/etc/letsencrypt/live/:ro
    restart: always
    stop_grace_period: 1m
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]

  cert-companion:
    image: nginx
    environment:
      - VIRTUAL_HOST=mail.fading-flame.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=mail.fading-flame.com
      - LETSENCRYPT_EMAIL=simonheiss87@gmail.com
    networks:
      - proxy-tier
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
  certs-volume:
    name: nginx-proxy_certs-volume
    external: true

networks:
  proxy-tier:
    external:
      name: nginx-proxy
